spring:
  application:
    name: payment-service

server:
  port: ${SERVER_PORT:8082}

traceflow:
  service:
    name: ${SERVICE_NAME:payment-service}
  environment:
    name: ${ENVIRONMENT:local}
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
