apiVersion: v1
kind: Service
metadata:
  name: {{ include "traceflow-lite.fullname" . }}-demo
  labels:
    {{- include "traceflow-lite.labels" . | nindent 4 }}
    app.kubernetes.io/name: traceflow-demo
spec:
  selector:
    app.kubernetes.io/name: traceflow-demo
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.demo.service.port }}
      targetPort: http
