apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "traceflow-lite.fullname" . }}-demo
  labels:
    {{- include "traceflow-lite.labels" . | nindent 4 }}
    app.kubernetes.io/name: traceflow-demo
automountServiceAccountToken: false
